In [1]:
#Import the needed libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Load the csv

df=pd.read_csv("Absenteeism-data.csv")
df.head(10)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   
5   3                  23  10/07/2015                     179   
6  10                  22  17/07/2015                     361   
7  20                  23  24/07/2015                     260   
8  14                  19  06/07/2015                     155   
9   1                  22  13/07/2015                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8  
7         4     0                          4  
8         2     0                         40  
9         1     1                          8

In [3]:
df.describe()

ID  Reason for Absence  Transportation Expense  \
count  700.000000          700.000000              700.000000   
mean    17.951429           19.411429              222.347143   
std     11.028144            8.356292               66.312960   
min      1.000000            0.000000              118.000000   
25%      9.000000           13.000000              179.000000   
50%     18.000000           23.000000              225.000000   
75%     28.000000           27.000000              260.000000   
max     36.000000           28.000000              388.000000   

       Distance to Work         Age  Daily Work Load Average  Body Mass Index  \
count        700.000000  700.000000               700.000000       700.000000   
mean          29.892857   36.417143               271.801774        26.737143   
std           14.804446    6.379083                40.021804         4.254701   
min            5.000000   27.000000               205.917000        19.000000   
25%           16.000000   31.000000               241.476000        24.000000   
50%           26.000000   37.000000               264.249000        25.000000   
75%           50.000000   40.000000               294.217000        31.000000   
max           52.000000   58.000000               378.884000        38.000000   

        Education    Children        Pets  Absenteeism Time in Hours  
count  700.000000  700.000000  700.000000                 700.000000  
mean     1.282857    1.021429    0.687143                   6.761429  
std      0.668090    1.112215    1.166095                  12.670082  
min      1.000000    0.000000    0.000000                   0.000000  
25%      1.000000    0.000000    0.000000                   2.000000  
50%      1.000000    1.000000    0.000000                   3.000000  
75%      1.000000    2.000000    1.000000                   8.000000  
max      4.000000    4.000000    8.000000                 120.000000

In [4]:
df.shape

(700, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.7+ KB


In [6]:
df_copy=df.copy()
df_copy.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [7]:
df_copy=df.drop(["ID"],axis=1)
df_copy.head(10)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   
5                  23  10/07/2015                     179                51   
6                  22  17/07/2015                     361                52   
7                  23  24/07/2015                     260                50   
8                  19  06/07/2015                     155                12   
9                  22  13/07/2015                     235                11   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   
5   38                  239.554               31          1         0     0   
6   28                  239.554               27          1         1     4   
7   36                  239.554               23          1         4     0   
8   34                  239.554               25          1         2     0   
9   37                  239.554               29          3         1     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  
5                          2  
6                          8  
7                          4  
8                         40  
9                          8

In [8]:
df_copy["Reason for Absence"].max()

28

In [9]:
df_copy["Reason for Absence"].min()

0

In [10]:
df_copy["Reason for Absence"].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [11]:
df_copy["Reason for Absence"].nunique()

28

In [12]:
len(df_copy["Reason for Absence"].unique())

28

In [13]:
sorted(df_copy["Reason for Absence"].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [14]:
#I created a dummy variable for the "Reason for Absence" column to analyzd it more

reason_columns=pd.get_dummies(df["Reason for Absence"])
type(reason_columns)
reason_columns.head()

0   1   2   3   4   5   6   7   8   9  ...  18  19  21  22  23  24  25  26  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   1   
1   1   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
3   0   0   0   0   0   0   0   1   0   0 ...   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   

   27  28  
0   0   0  
1   0   0  
2   0   0  
3   0   0  
4   0   0  

[5 rows x 28 columns]

In [15]:
reason_columns["check"]=reason_columns.sum(axis=1)
reason_columns.head()

0  1  2  3  4  5  6  7  8  9  ...    19  21  22  23  24  25  26  27  28  \
0  0  0  0  0  0  0  0  0  0  0  ...     0   0   0   0   0   0   1   0   0   
1  1  0  0  0  0  0  0  0  0  0  ...     0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0  ...     0   0   0   1   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0  ...     0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0  ...     0   0   0   1   0   0   0   0   0   

   check  
0      1  
1      1  
2      1  
3      1  
4      1  

[5 rows x 29 columns]

In [16]:
reason_columns["check"].unique()

array([1])

In [17]:
reason_columns=reason_columns.drop(["check"],axis=1)
reason_columns.head()

0   1   2   3   4   5   6   7   8   9  ...  18  19  21  22  23  24  25  26  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   1   
1   1   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
3   0   0   0   0   0   0   0   1   0   0 ...   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   

   27  28  
0   0   0  
1   0   0  
2   0   0  
3   0   0  
4   0   0  

[5 rows x 28 columns]

In [18]:
#I removed the zero from the first column

reason_columns=pd.get_dummies(df["Reason for Absence"],drop_first=True)
reason_columns.head()

1   2   3   4   5   6   7   8   9   10 ...  18  19  21  22  23  24  25  26  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   1   
1   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
3   0   0   0   0   0   0   1   0   0   0 ...   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   

   27  28  
0   0   0  
1   0   0  
2   0   0  
3   0   0  
4   0   0  

[5 rows x 27 columns]

In [19]:
#Group the reason for absence

df_copy.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [20]:
reason_columns.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 21, 22, 23, 24, 25, 26, 27, 28],
           dtype='int64')

In [21]:
df_copy=df_copy.drop(["Reason for Absence"],axis=1)
df_copy.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [22]:
#we group the reasons into 4 sections indicating 4 different types of issues

reason_1=reason_columns.loc[:,0:14].max(axis=1)
reason_2=reason_columns.loc[:,15:17].max(axis=1)
reason_3=reason_columns.loc[:,18:21].max(axis=1)
reason_4=reason_columns.loc[:,22:].max(axis=1)
reason_1.head(10)

0    0
1    0
2    0
3    1
4    0
5    0
6    0
7    0
8    0
9    0
dtype: uint8

In [23]:
df_copy.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [24]:
df_copy=pd.concat([df_copy,reason_1,reason_2,reason_3,reason_4],axis=1)
df_copy.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [25]:
df_copy.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [26]:
columns=['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', "Reason_0", "Reason_1", "Reason_2", "Reason_3"]

In [27]:
df_copy.columns=columns

In [28]:
df_copy.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_0  Reason_1  Reason_2  Reason_3  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

In [29]:
columns_reorderd=["Reason_0", "Reason_1", "Reason_2", "Reason_3",'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']
df_copy=df_copy[columns_reorderd]
df_copy.head()

Reason_0  Reason_1  Reason_2  Reason_3        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [30]:
df_copy_2=df_copy.copy()
df_copy_2.head()

Reason_0  Reason_1  Reason_2  Reason_3        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [31]:
df_copy_2["Date"].head()

0    07/07/2015
1    14/07/2015
2    15/07/2015
3    16/07/2015
4    23/07/2015
Name: Date, dtype: object

In [32]:
df_copy_2["Date"]=pd.to_datetime(df_copy_2["Date"],format="%d/%m/%Y")
df_copy_2["Date"].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [33]:
df_copy_2["Date"][0].year

2015

In [34]:
df_copy_2["Date"][0].month

7

In [35]:
list_of_month=[]

for i in range(700):
    list_of_month.append(df_copy_2["Date"][i].month)
    
list_of_month

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 

In [36]:
df["month_value"]=list_of_month

In [37]:
list_of_day=[]

for i in range(700):
    list_of_day.append(df_copy_2["Date"][i].day)
    
#list_of_day
df["day_value"]=list_of_day

In [38]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  month_value  day_value  
0         2     1                          4            7          7  
1         1     0                          0            7         14  
2         0     0                          2            7         15  
3         2     0                          4            7         16  
4         2     1                          2            7         23

In [39]:
#or an alternative to get the da_value is by writing a function and calling it 

#def day_of_week(x):
#    val=x.weekday()
#    return val

#df["day_valuess"]=df["Date"].apply(day_of_week)

In [40]:
df["Education"].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [41]:
df["Education"]=df["Education"].map({1:0,2:1,3:1,4:1})

In [42]:
df["Education"].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [43]:
df_copy=df.copy()
df_copy.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  month_value  day_value  
0         2     1                          4            7          7  
1         1     0                          0            7         14  
2         0     0                          2            7         15  
3         2     0                          4            7         16  
4         2     1                          2            7         23

In [44]:
df_copy["Absenteeism Time in Hours"].median()

3.0

In [45]:
targets=np.where(df_copy["Absenteeism Time in Hours"] > df_copy["Absenteeism Time in Hours"].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [46]:
df_copy["Excessive Absenteeism"]=targets

In [47]:
#df_copy=df.drop(columns=["Absenteeism Time in Hours"],axis=1)
df_copy.shape

(700, 15)

In [48]:
df is df_copy

False

In [49]:
#If I decide to reshuffle the columns

#df_copy.columns.values
#col=[ 'Excessive Absenteeism','ID', 'Reason for Absence', 'Date', 'Transportation Expense',
#       'Distance to Work', 'Age', 'Daily Work Load Average',
#       'Body Mass Index', 'Education', 'Children', 'Pets', 'month_value',
#       'day_value']

#df_copy=df_copy[col]
#df_copy.head()

In [50]:
df_copy=df_copy.drop(columns=["Date"],axis=1)

In [51]:
unscaled_inputs=df_copy.iloc[:,1:]
unscaled_inputs.shape

(700, 13)

In [62]:
unscaled_targets=df_copy.iloc[:,1]
unscaled_targets.shape

(700,)

In [98]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_x.fit(unscaled_inputs)
scaled_inputs=sc_x.transform(unscaled_inputs)

/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [99]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(scaled_inputs,unscaled_targets,test_size=0.2)

In [100]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0,penalty="l1")
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [101]:
classifier.score(x_train,y_train)

0.6553571428571429

In [102]:
from sklearn.metrics import classification_report,confusion_matrix

cr= classification_report(y_test,y_pred)
cr

/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/nikhilshetty/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n           0       0.89      1.00      0.94         8\n           1       0.60      0.60      0.60         5\n           2       0.00      0.00      0.00         1\n           4       0.00      0.00      0.00         2\n           7       0.50      0.50      0.50         2\n           8       0.00      0.00      0.00         2\n           9       0.00      0.00      0.00         1\n          10       0.00      0.00      0.00         4\n          11       0.00      0.00      0.00         3\n          12       0.00      0.00      0.00         2\n          13       0.29      0.44      0.35         9\n          14       0.00      0.00      0.00         2\n          15       0.00      0.00      0.00         1\n          16       0.00      0.00      0.00         1\n          18       0.00      0.00      0.00         2\n          19       0.17      0.33      0.22         3\n          22       0.20      0.33      0.25         3\n       

In [103]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,

In [61]:
classifier.coef_

array([[-3.40825414e+00,  1.38787091e-01,  0.00000000e+00,
        -1.61673218e-01,  1.22175007e-01,  3.51878570e-01,
         0.00000000e+00,  2.01132680e-01,  0.00000000e+00,
         0.00000000e+00,  4.85639812e-02,  2.27500825e-01,
        -1.98704961e+00],
       [-3.24589808e+00,  0.00000000e+00,  0.00000000e+00,
         5.93444536e-01, -1.21186357e-01, -5.29769261e-01,
         4.15180058e-01,  1.59585822e-01,  0.00000000e+00,
        -3.85280785e-02,  0.00000000e+00, -1.72121311e-01,
         1.55713283e+00],
       [-3.51974306e-01,  2.24634750e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.40638712e-01,  0.00000000e+00,  0.00000000e+00,
         8.96258326e-02,  1.22214516e-01,  0.00000000e+00,
         0.00000000e+00],
       [-4.41153710e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  9.21271413e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -3.31156135e

In [57]:
classifier.intercept_

array([ -7.90320726,  -8.96222097,  -5.90173371,  -5.78663529,
        -5.89053987,  -5.74190895,  -5.63980135,  -5.14703013,
        -5.11262802,  -5.73531475,  -4.31908602,  -3.77631726,
        -5.53302882,  -3.00803099,  -4.05413707,  -5.55537984,
        -5.6496055 ,  -5.83545379,  -3.91104034,  -3.86330483,
        -5.12634984,  -4.81144842,  -1.96029317,  -5.64369399,
        -3.92955491,  -6.77106507,  -7.39854031, -15.62795733])

In [97]:
predicted_proba=classifier.predict_proba(x_test)
predicted_proba

array([[3.41677402e-06, 7.35101651e-05, 2.17718566e-03, ...,
        3.69086029e-01, 3.66730838e-03, 1.70712553e-02],
       [1.07112279e-03, 3.88436092e-03, 4.59280488e-03, ...,
        4.25747975e-02, 1.04097723e-07, 1.32770727e-12],
       [5.70138258e-01, 7.31616992e-02, 5.33892229e-03, ...,
        1.74985335e-08, 1.39946100e-08, 1.79340891e-23],
       ...,
       [1.18069654e-04, 6.06007808e-04, 5.64653617e-03, ...,
        9.86060300e-02, 4.86841789e-06, 2.71369990e-07],
       [4.32343086e-05, 1.73915623e-04, 4.15087418e-03, ...,
        6.75104465e-02, 4.00627638e-05, 9.37750383e-05],
       [6.91151011e-05, 1.80495354e-07, 8.90276904e-04, ...,
        7.15364897e-04, 3.56190501e-03, 5.52316472e-01]])

In [104]:
import pickle

In [105]:
with open("model","wb") as file:
    pickle.dump(classifier,file)

In [106]:
with open("scaler","wb") as file:
    pickle.dump(scaled_inputs,file)